version: '2.2'
services:
  apollo:
    image: apollo-all:1.5.1
    container_name: apollo-all-1.5.1
    network_mode: "host"
#    restart: always
#    volumes:
#    - ./application-ldap.yml:/apollo-portal/config/application-ldap.yml:ro #ldap配置文件挂载路径
# 启动前,确认对应环境的数据库已经建立，否则apollo无法启动.
# 默认端口:portal:8070; dev:8080,8090; fat:8081,8091; uat:8082,8092; pro:8083,8093
    environment:
      PORTAL_DB: jdbc:mysql://172.24.28.3:13306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: yzf
#      PORTAL_PORT: 80
#      PORTAL_LDAP: "TRUE"

      DEV_DB: jdbc:mysql://172.24.28.3:13306/ApolloConfigDB?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: yzf
      
#      FAT_DB: jdbc:mysql://172.24.28.3:13306/ApolloConfigDBFat?characterEncoding=utf8
#      FAT_DB_USER: root
#      FAT_DB_PWD: password
#
#      #UAT_DB: jdbc:mysql://172.24.28.3:13306/ApolloConfigDBUat?characterEncoding=utf8
#      UAT_DB_USER: root
#      UAT_DB_PWD: password
#
#      #PRO_DB: jdbc:mysql://172.24.28.3:13306/ApolloConfigDBPro?characterEncoding=utf8
#      PRO_DB_USER: root
#      PRO_DB_PWD: password
